language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

notifications:
  slack: pachalenlab:cvdNAbM5k3SxFn339Vm4ttxf

before_install:
    - chmod +x gradlew

script:
    - ./gradlew build
